### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AmirTalaei** [eaulisa/MyFEMuS#1]
Dear All,

I tried to compile MyFEMus (particleFSI branch), But when I ran "cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="[Debug Release RelWithDebInfo MinSizeRel None]"  ../"
I faced the attached error.
[Error.txt](https://github.com/eaulisa/MyFEMuS/files/2461443/Error.txt)

I would be so pleased if you could guide me on this issue.

Thanks,
Amir

**Comment by eaulisa** [comment]
This is kind of an old branch

please move to the master one

you need to install PETSC (on the maint branch) with the following configure options

/configure --with-debugging=0 COPTFLAGS="-O3 -march=native -mtune=native" CXXOPTFLAGS="-O3 -march=native -mtune=native" FOPTFLAGS="-O3 -march=native -mtune=native" --download-openmpi=1 --download-fblaslapack=1 --download-hdf5=1 --download-metis=1 --download-parmetis=1 --with-shared-libraries=1 --download-blacs=1 --download-scalapack=1 --download-mumps=1 --download-suitesparse

also you now need to instal SLEPC (it is probably not needed 100%, but I would install it)

try with this and let me know

Eugenio

 



Eugenio Aulisa

Department of Mathematics and Statistics,
Texas Tech University
Lubbock TX, 79409-1042
room: 226
http://www.math.ttu.edu/~eaulisa/
phone: (806) 834-6684
fax: (806) 742-1112




________________________________________

**Comment by AmirTalaei** [comment]
Dear Prof. Aulisa,

Thanks for your quick response.

I installed PETSc by replacing your suggested configure options in "/home/amir/femus/MyFEMuS/contrib/scripts/install_petsc.sh".
I also installed SLEPc version 3.10.0 (based on "http://slepc.upv.es/documentation/instal.htm").

But when I ran "cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="[Debug Release RelWithDebInfo MinSizeRel None]" ../" I faced the attached error.

I would be so pleased if you could guide me on this issue.

Thanks,
Amir
[Error.txt](https://github.com/eaulisa/MyFEMuS/files/2463312/Error.txt)

**Comment by eaulisa** [comment]
It looks like it cannot find SLEPC, try to set up a variable 
 
export SLEPC_DIR = ... 

Eugenio



Eugenio Aulisa

Department of Mathematics and Statistics,
Texas Tech University
Lubbock TX, 79409-1042
room: 226
http://www.math.ttu.edu/~eaulisa/
phone: (806) 834-6684
fax: (806) 742-1112




________________________________________

**Comment by AmirTalaei** [comment]
Dear Prof. Aulisa,

In the last post I had already set up "export SLEPC_DIR=/home/bijan/femus/slepc-3.10.0".

Thanks,
Amir

**Comment by AmirTalaei** [comment]
Dear Prof. Aulisa,

In the last post I had already set up "export SLEPC_DIR=/home/amir/femus/slepc-3.10.0".

Thanks,
Amir

**Comment by eaulisa** [comment]
It seams to me that still it cannot find slepc, or maybe there is something wrong in how slepc was installed
In any case you should be capable to run femus even without slepc. Some of the applications won't work.

inside the CMakeList.txt file find and comment these lines
 
# Find Slepc Library (optional)
#FIND_PACKAGE(SLEPc)
#MESSAGE(STATUS "SLEPC_FOUND = ${SLEPC_FOUND}")
#SET(HAVE_SLEPC 0)
#IF(SLEPC_FOUND)
#  SET(HAVE_SLEPC 1)
#ENDIF(SLEPC_FOUND)

and set instead 

SET(HAVE_SLEPC 0)

Also I generally use cmake-gui to configure and generate femus, rather than the command line.
It helps me to understand more if something is wrong.





Eugenio Aulisa

Department of Mathematics and Statistics,
Texas Tech University
Lubbock TX, 79409-1042
room: 226
http://www.math.ttu.edu/~eaulisa/
phone: (806) 834-6684
fax: (806) 742-1112




________________________________________

**Comment by AmirTalaei** [comment]
Dear Prof. Aulisa,

Based on your instructions I changed 'CMakeList.txt' and it worked, But when I ran "make -j8" I faced the attached error.
[Error.txt](https://github.com/eaulisa/MyFEMuS/files/2470035/Error.txt)

I would be so pleased if you could guide me on this issue.

Thanks,
Amir

**Comment by eaulisa** [comment]
This is beacuse you have an outdated version of gcc, probably 3 or 4

we use gcc-7 with x11 capabilities

This comes by default on the new open suse 15.0, so I am not sure what to recommend you

Eugenio Aulisa

Department of Mathematics and Statistics,
Texas Tech University
Lubbock TX, 79409-1042
room: 226
http://www.math.ttu.edu/~eaulisa/
phone: (806) 834-6684
fax: (806) 742-1112




________________________________________

**Comment by AmirTalaei** [comment]
Dear Prof. Aulisa,

I changed gcc version to 7.3.0 and 'MyFEMuS' compiled successfully.

Thanks again for your helpful responses.

Kind regards,
Amir
